"""Claim 6: tunnel key algorithm and server identity verification.

The document states:
  a) "The tunnel keys are ECDSA over the NIST P-256 curve."
     (This answers a customer question that had assumed ECDSA 521.)
  b) "the keyfile is the private key the Connector authenticates with, and
     server_key holds the server's public key, which the Connector uses to
     verify it is connecting to the right server. If that identity does not
     match, the connection is rejected."
  c) "the Connector does not look for keys automatically on the system nor use
     the SSH agent, it only uses the key declared in the configuration."

Part (a) cannot be verified from this repository: keyfiles are generated by
the infrastructure team, not by pytun. It is verified here by cryptographically
parsing real customer keys. Parts (b) and (c) are properties of ssh_connect().
"""
import inspect
import os
import pathlib

import pytest
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec

REAL_CONFIGS = pathlib.Path("/home/alejandro-cantero/VMShared/configuracion_connector/configs")

requires_real_configs = pytest.mark.skipif(
    not REAL_CONFIGS.is_dir(),
    reason="real customer configs not available at %s" % REAL_CONFIGS,
)


def tunnel_configs():
    if not REAL_CONFIGS.is_dir():
        return []
    return sorted(REAL_CONFIGS.glob("*.ini"))


def keyfiles_from_configs():
    """Resolve every keyfile the way the connector does: relative to the config dir."""
    import configparser
    found = []
    for ini in tunnel_configs():
        cfg = configparser.ConfigParser()
        cfg.read(ini)
        keyfile = cfg["tunnel"]["keyfile"]
        path = pathlib.Path(keyfile)
        if not path.is_absolute():
            path = ini.parent / keyfile
        found.append((ini.name, path))
    return found


# ---------------------------------------------------------------- claim 6 (a)

@requires_real_configs
@pytest.mark.parametrize("ini_name,keyfile", keyfiles_from_configs(),
                         ids=[n for n, _ in keyfiles_from_configs()] or None)
def test_tunnel_private_key_is_ecdsa_on_nist_p256(ini_name, keyfile):
    """The load-bearing assertion: ECDSA, and specifically the P-256 curve.

    A PEM header of 'EC PRIVATE KEY' proves it is elliptic curve but says
    nothing about the curve, so the key is parsed and the curve interrogated.
    """
    assert keyfile.is_file(), "keyfile %s referenced by %s is missing" % (keyfile, ini_name)

    key = serialization.load_pem_private_key(keyfile.read_bytes(), password=None)

    assert isinstance(key, ec.EllipticCurvePrivateKey), (
        "%s is %s, not ECDSA" % (keyfile.name, type(key).__name__)
    )
    assert isinstance(key.curve, ec.SECP256R1), (
        "%s uses curve %s, not NIST P-256 (secp256r1)" % (keyfile.name, key.curve.name)
    )
    assert key.curve.key_size == 256
    # Explicitly refute the customer's ECDSA-521 premise.
    assert key.curve.key_size != 521


@requires_real_configs
def test_no_tunnel_key_is_rsa_dsa_or_a_different_curve():
    """Guards against a mixed fleet: every key must match the published answer."""
    keys = keyfiles_from_configs()
    assert keys, "no tunnel configs found"

    curves = {}
    for ini_name, keyfile in keys:
        key = serialization.load_pem_private_key(keyfile.read_bytes(), password=None)
        curves[keyfile.name] = key.curve.name

    assert set(curves.values()) == {"secp256r1"}, curves


@requires_real_configs
def test_private_keys_have_no_passphrase():
    """Cross-checks a related claim.

    Claim 14 lists PasswordRequiredException as meaning "the private key has a
    passphrase, something not contemplated in the standard configuration", and
    the tunnel config docs require a passwordless key. Loading with
    password=None must therefore succeed.
    """
    for ini_name, keyfile in keyfiles_from_configs():
        serialization.load_pem_private_key(keyfile.read_bytes(), password=None)


@requires_real_configs
def test_server_key_is_a_known_hosts_entry_for_the_configured_server():
    """Claim 6 (b): server_key holds the server's public key.

    It must be a known_hosts-format entry naming the host and port the tunnel
    actually connects to — otherwise verification could not bind to it.
    """
    import configparser

    for ini in tunnel_configs():
        cfg = configparser.ConfigParser()
        tunnel = cfg["tunnel"] if cfg.read(ini) and "tunnel" in cfg else None
        assert tunnel is not None, ini

        server_key = pathlib.Path(tunnel["server_key"])
        if not server_key.is_absolute():
            server_key = ini.parent / tunnel["server_key"]
        assert server_key.is_file(), "server_key %s missing" % server_key

        content = server_key.read_text().strip()
        host = tunnel["server_host"]
        port = tunnel["server_port"]

        assert "[%s]:%s" % (host, port) in content, (
            "%s does not pin the configured server %s:%s" % (server_key.name, host, port)
        )
        # A host key entry carries an algorithm and base64 blob.
        parts = content.split()
        assert len(parts) >= 3, content
        assert parts[1].startswith("ecdsa-sha2-") or parts[1].startswith("ssh-"), parts[1]


# ------------------------------------------------------------ claim 6 (b)+(c)

def test_ssh_connect_rejects_unknown_host_keys():
    """Claim 6 (b): a mismatched server identity means the connection is refused.

    Asserted on the source of ssh_connect() because reaching the real branch
    requires a live SSH server. RejectPolicy is what makes a mismatch fatal;
    AutoAddPolicy or WarningPolicy would silently accept an impostor.
    """
    from tunnel_infra.TunnelProcess import TunnelProcess

    source = inspect.getsource(TunnelProcess.ssh_connect)
    assert "RejectPolicy" in source
    assert "AutoAddPolicy" not in source
    assert "WarningPolicy" not in source
    assert "load_system_host_keys" in source


def test_ssh_connect_disables_key_discovery_and_the_agent():
    """Claim 6 (c): no automatic key lookup, no SSH agent."""
    from tunnel_infra.TunnelProcess import TunnelProcess

    source = inspect.getsource(TunnelProcess.ssh_connect)
    assert "look_for_keys=False" in source
    assert "allow_agent=False" in source
    assert "key_filename=self.key_file" in source


def test_reject_policy_raises_on_an_unknown_host_key():
    """Prove RejectPolicy actually rejects, rather than trusting the name."""
    import paramiko

    policy = paramiko.RejectPolicy()
    client = paramiko.SSHClient()
    # RejectPolicy logs the rejection through the transport before raising;
    # there is no transport outside a real connection, so stub the log sink.
    client._log = lambda *args, **kwargs: None
    key = paramiko.ECDSAKey.generate()

    with pytest.raises(paramiko.SSHException):
        policy.missing_host_key(client, "unexpected-host", key)


def test_ssh_connect_uses_a_ten_second_connect_timeout():
    """Cross-checks claim 11: '10 seconds to establish the SSH connection'."""
    from tunnel_infra.TunnelProcess import TunnelProcess

    source = inspect.getsource(TunnelProcess.ssh_connect)
    assert "timeout=10" in source
